const API='https://apexgrid.onrender.com';
const S={world:{},cars:[],events:[],radio:[],selected:null,lastUpdate:0,history:[]};const $=id=>document.getElementById(id);const ctx=$('map').getContext('2d');
async function get(p){const r=await fetch(API+p);if(!r.ok)throw Error();return r.json()}
function row(a,b){return `<div class="row"><span>${a}</span><b>${b??'—'}</b></div>`}
function render(){const w=S.world||{}; $('title').textContent=w.title||'APEXGRID World';$('msg').textContent=w.message||'Autonomous motorsport simulation';$('season').textContent=w.season||'—';$('round').textContent=w.round??'—';$('track').textContent=w.track||'Track';$('lap').textContent=w.lap_total?`LAP ${w.lap||0} / ${w.lap_total}`:(w.state||'WAITING');$('state').textContent=w.state||'WAITING';$('flag').textContent=w.race_control||'GREEN';$('weather').textContent=(w.weather||'CLEAR').toUpperCase();$('clock').textContent=w.updated_at?new Date(w.updated_at).toLocaleTimeString():'—';$('carcount').textContent=`${S.cars.length} / 20`;
const g=w.track_geometry||{};$('trackstats').textContent=`${g.length_km??'—'} km · ${g.corners??'—'} corners · Wet ${Number(w.track_wetness||0).toFixed(0)}%`;
$('world').innerHTML=[row('Session',w.state),row('Air',w.air_temp!=null?`${w.air_temp} °C`:'—'),row('Track',w.track_temp!=null?`${w.track_temp} °C`:'—'),row('Humidity',w.humidity!=null?`${w.humidity}%`:'—'),row('Wind',w.wind_speed!=null?`${w.wind_speed} m/s`:'—'),row('Wetness',`${Number(w.track_wetness||0).toFixed(1)}%`),row('Race control',w.race_control||'GREEN')].join('');
$('cars').innerHTML=S.cars.map((c,i)=>`<div class="car ${c.dnf?'dnf':''} ${S.selected===c.driver_id?'sel':''}" data-id="${c.driver_id}"><span class="pos">P${c.position||i+1}</span><span class="name"><b>${c.driver_name}</b><small class="team">${c.team} · #${c.number||'—'} · S${c.sector||1}</small></span><span>${c.dnf?'DNF':(c.gap||'—')}</span></div>`).join('')||'<div class="selected">Waiting for the grid…</div>';
$('events').innerHTML=S.events.slice(-14).reverse().map(e=>`<div class="event"><b>${e.kind||'EVENT'}</b><span>${e.lap?`L${e.lap} · `:''}${e.text||''}</span></div>`).join('')||'<div class="event">No events yet.</div>';
const st=w.standings||[];$('standings').innerHTML=st.length?st.slice(0,10).map((x,i)=>`<div class="row"><span><strong>P${i+1}</strong> ${x.driver_name}<small>${x.team_name||''}</small></span><b>${x.points} PTS</b></div>`).join(''):'No completed races in this season yet.';
$('calendar').innerHTML=(w.calendar||[]).map(r=>`<div class="calendar-row ${Number(w.round)===r.round?'active':''}"><span>R${String(r.round).padStart(2,'0')}</span><b>${r.track}</b><em>${r.laps} LAPS</em></div>`).join('')||'Season calendar will appear when the next season starts.';
if(S.selected)selectCar(S.selected);document.querySelectorAll('.car').forEach(e=>e.onclick=()=>{S.selected=e.dataset.id;selectCar(S.selected)});
$('radio').innerHTML=S.radio.slice(-10).reverse().map(x=>`<div class="radio-line"><b>${x.driver||'RADIO'}</b><span>${x.text||''}</span></div>`).join('')||'No radio traffic yet.';draw();}
function selectCar(id){const c=S.cars.find(x=>x.driver_id===id);if(!c)return;S.selected=id;$('selected').innerHTML=`<div class="bigdriver"><b>P${c.position||'—'} · ${c.driver_name}</b><span>${c.team} · Car #${c.number||'—'} · Sector ${c.sector||1}</span></div>`+[row('Position',`P${c.position||'—'}`),row('Speed',`${c.speed||0} km/h`),row('Heading',`${c.heading||0}°`),row('Last lap',c.lap_time?`${c.lap_time}s`:'—'),row('Gap',c.gap),row('Fuel',`${c.fuel??'—'}%`),row('Energy / ERS',`${c.energy??'—'}%`),row('Coordinates',`${Number(c.x||0).toFixed(1)}, ${Number(c.y||0).toFixed(1)}`)].join('');const h=c.health||{};$('systems').innerHTML=['engine','gearbox','battery','brakes','suspension','aero','cooling'].map(k=>`<div class="barrow"><span>${k.toUpperCase()}</span><b>${h[k]??100}%</b><i><em style="width:${Math.max(0,Math.min(100,h[k]??100))}%"></em></i></div>`).join('');$('strategy').innerHTML=[row('Tyre',c.tyres),row('Wear',`${c.tyre_wear??0}%`),row('Stint',`${c.tyre_laps??0} laps`),row('Pit stops',c.pit_stops??0),row('Driver rating',c.driver_rating??'—'),row('Morale',c.morale??'—')].join('')}
function draw(){ctx.clearRect(0,0,900,520);ctx.fillStyle='#080b10';ctx.fillRect(0,0,900,520);const pts=S.world.track_geometry?.points||[];if(pts.length){ctx.strokeStyle='#252d38';ctx.lineWidth=62;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();ctx.strokeStyle='#aab2bd';ctx.lineWidth=2;ctx.setLineDash([11,10]);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.fillRect(112,370,16,20)}else{ctx.fillStyle='#8e9aaa';ctx.font='16px system-ui';ctx.fillText('Waiting for track geometry…',40,60)}S.cars.forEach(c=>{if(c.x==null||c.y==null)return;ctx.save();ctx.translate(c.x,c.y);ctx.rotate((Number(c.heading||0))*Math.PI/180);ctx.globalAlpha=c.dnf?.3:1;ctx.fillStyle=c.color||'#fff';ctx.beginPath();ctx.roundRect(-9,-4,18,8,3);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 10px system-ui';ctx.rotate(-(Number(c.heading||0))*Math.PI/180);ctx.fillText(String(c.position||''),11,-8);if(S.selected===c.driver_id){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,13,0,Math.PI*2);ctx.stroke()}ctx.restore()})}
async function refresh(){try{const [w,h]=await Promise.all([get('/world'),get('/history')]);S.world=w;S.cars=w.cars||[];S.events=h.events||S.events;S.lastUpdate=performance.now();$('status').textContent='ONLINE';render()}catch(e){$('status').textContent='OFFLINE'}}
function ws(){try{const s=new WebSocket('wss://apexgrid.onrender.com/ws/live');s.onopen=()=>$('status').textContent='LIVE';s.onmessage=e=>{const m=JSON.parse(e.data);S.lastUpdate=performance.now();if(m.type==='world'){S.world=m.data;S.cars=m.data.cars||S.cars}if(m.type==='event'){S.events.push(m.data);if(m.data.kind==='RADIO')S.radio.push({driver:m.data.driver||'RADIO',text:m.data.text})}render()};s.onclose=()=>setTimeout(ws,3000);s.onerror=()=>s.close()}catch(e){setTimeout(ws,3000)}}
draw();refresh();ws();setInterval(refresh,10000);